### ISSUE TITLE
Can't find the password for vault id start with "-"

### ISSUE THREAD

**Issue by pttri** [purejava/keepassxc-proxy-access#11]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-cryptomator/issues?q=) for duplicates

### Summary

The cryptomator's vault id starts with hyphen won't be able to locate the saved password in Keepass

### What software is involved?

- Operating System: Ubuntu 22.04.2 LTS
- Cryptomator: 1.6.17
- keepassxc-cryptomator-1.2.1.jar
- KeePassXC: 2.6.6 (ubuntu official package)

### Steps to Reproduce

Have no idea how to reproduce the cryptomator's vault ID with hyphen in the beginning. (`-Ucq0zYwVtth`)

But when I remove the vault, and successfully import it again to Cryptomator with new ID (`tIcNZ-5GLXQ_`), everything is normal.

### Expected Behavior

The saved vault would be opened successfully

### Actual Behavior

The saved vault can't auto-open, it would display the form to enter password even the new record was already successfully created in Keepass

### Reproducibility

Always

### Relevant Log Output

```shell
11:00:33.703 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault -Ucq0zYwVtth
11:00:38.109 [App Scheduled Executor 02] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/abc/.config/Cryptomator/settings.json
11:01:19.874 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No logins found
11:01:19.875 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault -Ucq0zYwVtth
11:01:35.608 [App Background Thread 017] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No logins found
11:01:35.715 [App Background Thread 017] INFO  o.p.i.keychain.KeePassXCAccess - Password successfully stored for vault -Ucq0zYwVtth
11:01:35.717 [JavaFX Application Thread] INFO  o.c.ui.unlock.UnlockWorkflow - Unlock of 'somevault' succeeded.
11:02:56.325 [fuseMount-6-main] INFO  org.cryptomator.common.vaults.Vault - Unmounted vault 'somevault'
11:02:56.333 [JavaFX Application Thread] INFO  o.cryptomator.ui.lock.LockWorkflow - Lock of somevault succeeded.
11:02:57.418 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No logins found
11:02:57.418 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault -Ucq0zYwVtth
11:03:12.762 [JavaFX Application Thread] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No logins found
11:03:12.763 [JavaFX Application Thread] INFO  o.p.i.keychain.KeePassXCAccess - No password found for vault -Ucq0zYwVtth
11:03:22.963 [App Background Thread 020] INFO  org.purejava.KeepassProxyAccess - org.purejava.KeepassProxyAccessException: ErrorCode: 15, No logins found
11:03:23.067 [App Background Thread 020] INFO  o.p.i.keychain.KeePassXCAccess - Password successfully stored for vault -Ucq0zYwVtth
11:03:23.068 [JavaFX Application Thread] INFO  o.c.ui.unlock.UnlockWorkflow - Unlock of 'somevault' succeeded.
11:03:58.879 [fuseMount-7-main] INFO  org.cryptomator.common.vaults.Vault - Unmounted vault 'somevault'
11:03:58.889 [JavaFX Application Thread] INFO  o.cryptomator.ui.lock.LockWorkflow - Lock of somevault succeeded.
```

### Anything else?

The new created record in KeepassXC is:
- Having error in URL field
- The tittle is empty. 

![image](https://user-images.githubusercontent.com/7644428/221338409-512041d3-ce4b-49c3-a087-de3f39d19158.png)

**Comment by purejava** [comment]
Thanks for reporting this issue. I investigated it.

In your case Cryptomator obviously generated a vault ID stating with "-". The ID is generated randomly. This library saves the vault ID in the URL field of an entry in the KeePassXC database, as it can be seen in your screenshot, from where it can be retrieved.

When this library requests a vault password, KeePassXC searches the database for the URL it got within the request from the library and matches it with the URL field of the entries in the KeePassXC database.  I debugged the KeePassXC code and this is where it fails:
```cpp
QUrl siteQUrl(siteUrl);
```
https://github.com/keepassxreboot/keepassxc/blob/56178f976a39ecba049fdadae2b051e533cba170/src/browser/BrowserService.cpp#L1080

This creates a `QUrl` object [from the URL](https://doc.qt.io/qt-5/qurl.html#QUrl-3).

Doing this with an URL starting with "-" creates an empty object.

<img width="334" alt="Bildschirm­foto 2023-02-25 um 10 52 23" src="https://user-images.githubusercontent.com/1822238/221351270-a8217721-cce1-418d-82b5-9ecf91c44916.png">

In the end, KeePassXC does not return a matched URL.

Unfortunately, there is nothing we can do about it, as the handling on the KeePassXC site for URLs is correct.

You already described the workaround for this case: altering the vault ID. This can be done directly in the Cryptomator settings file `~/.config/Cryptomator/settings.json`.

**Comment by pttri** [comment]
Thanks for your quick investigation. It's true we can't do anything on KeepassXC or Cryptomator side.

Therefore, if possible, I would suggest to have some notifications in this case, so future users will know what to do. Maybe the quick one is having a message on the log file (Eg: "Please change your vault ID...").

It would be nice if there is a wiki for this issue also. 😀

**Comment by purejava** [comment]
> Therefore, if possible, I would suggest to have some notifications in this case, so future users will know what to do. Maybe the quick one is having a message on the log file (Eg: "Please change your vault ID...").

I think this would be a bit overdone, as this should occur in rare cases.

> It would be nice if there is a wiki for this issue also. 😀

That's a good idea. Done, see: [Known-issues](https://github.com/purejava/keepassxc-cryptomator/wiki/Know-issues)
