### ISSUE TITLE
Library only works if browser integration is enabled?

### ISSUE THREAD

**Issue by CallMeFlanby** [purejava/keepassxc-proxy-access#13]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-proxy-access/issues?q=) for duplicates

### Summary

It appears that this library only works if the browser integration is enabled.

### What software is involved?

- Operating System: Windows 10
- Operating System: Linux Mint 21.1 (tested on this system too)
- KeePassXC: 2.7.4
- keepassxc-proxy-access: 1.2.1

### Steps to Reproduce

1. Install a new instance of KeePassXC
2. Open the database but do not change any settings
2.1. Maybe check if in the database settings (Database -> Database settings -> Browser integration is disabled as it should show a banner OR Tools -> Settings -> Browser Integration and check if the first box (Enable browser integration) is unticked).
3. Try to use this library

### Expected Behavior

Library should connect without any problems. 

### Actual Behavior

(all other steps above in "Steps to Reproduce")
4. The connect method should not work and therefore nothing else

### Reproducibility

Always

### Anything else?

I don't know if this can really be fixed. Probably the best practice is to add it to the readme and troubleshoot.

**Comment by purejava** [comment]
Browser integration needs to be enabled in KeePassXC, as this is the interface this library uses to connect with and talk to KeePassXC. At least you need a way to communicate between not otherwise related processes or an application and library in this case.
