### ISSUE TITLE
[WindowsConnection] No connection if user is local

### ISSUE THREAD

**Issue by CallMeFlanby** [purejava/keepassxc-proxy-access#41]
Hello,

We have found a new issue related to the library. 
We implemented this library and noticed that only one colleague could not use our implementation. We looked further into the problem and maybe found out the issue. We compared their system's pipes with the ones from another colleague and noticed that their pipes looked a little bit different at the end:

Colleague René Kaufmann: 
`\\.\\pipe\\org.keepassxc.KeePassXC.BrowserServer_Ren� Kaufmann (lokal)`
Colleague Christian Mustermann:
`\\.\\pipe\\org.keepassxc.KeePassXC.BrowserServer_christian.mustermann`

At first we thought it was related with the "é", represented with the question mark in the pipe, but then looking further into your implementation, we changed our mind and we currently think it is related with the "(lokal)" part of the pipe, as we suppose that the method "System.getenv("USERNAME")" returns "Ren� Kaufmann". We haven't tested if the method really returns that value.

What do you think it could be the problem? Maybe what we mean or something else?
Looking forward to reading from you.

I've marked the part of the code that calls the pipe:
https://github.com/purejava/keepassxc-proxy-access/blob/c5394137e45895894e7ebb3c7814f752027371a9/src/main/java/org/keepassxc/WindowsConnection.java#L40C99-L40C99

Disclaimer: the surname of both colleagues was changed in order to protect their privacy.

Have a great weekend.

Kind regards from Rostock

**Comment by purejava** [comment]
Hi,

well, you do not provide any information on how René Kaufmann's account differs from the other accounts. How is it set up? What kind of account is it?

I installed a local user on my Windows box for testing purposes, but her pipe looks exactly like the pipes of others, that is, without this "(local)" suffix.

**Comment by CallMeFlanby** [comment]
> Hi,
> 
> well, you do not provide any information on how René Kaufmann's account differs from the other accounts. How is it set up? What kind of account is it?
> 
> I installed a local user on my Windows box for testing purposes, but her pipe looks exactly like the pipes of others, that is, without this "(local)" suffix.

Hi, I'll ask around and let you know how to reproduce it.

Thanks for your first reply.

Best regards

**Comment by CallMeFlanby** [comment]
Hi, thanks for closing this issue. I couldn't reach the colleague anymore. I will come back to this if it happens again. 

Have a great thursday.

Best regards from Warnemünde
