### ISSUE TITLE
What's the password of Test.kdbx?

### ISSUE THREAD

**Issue by realpixelcode** [purejava/keepassxc-proxy-access#55]
It would be very handy if the password of [`Test.kdbx`](https://github.com/purejava/keepassxc-proxy-access/blob/develop/src/test/resources/Test.kdbx) was published so that contributors could easily reproduce the [`UnlockedDatabaseTest.java`](https://github.com/purejava/keepassxc-proxy-access/blob/develop/src/test/java/org/purejava/UnlockedDatabaseTest.java).

**Comment by purejava** [comment]
The PW is `test`.
