### ISSUE TITLE
Cannot close connection to KeePassXC

### ISSUE THREAD

**Issue by CallMeFlanby** [purejava/keepassxc-proxy-access#7]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-proxy-access/issues?q=) for duplicates

### Summary

After connecting the connection cannot be closed.

### What software is involved?

- Operating System: Linux Mint 20.3 Cinnamon
- keepassxc-proxy-access: 1.1.1
- KeePassXC: 2.7.1
- Eclipse: 2021-12
- Java: 17

### Steps to Reproduce

1. Create a new KeepassProxyAccess
2. Connect
```
KeepassProxyAccess kpa = new KeepassProxyAccess();
kpa.connect();
```

### Expected Behavior

Option to close the connection or as described in the code 
> The closing of the connection is handled automatically.

### Actual Behavior

Program runs and the connection is never closed. I don't know when this connection should be closed, had a program running for ten minutes and nothing happened. 

### Reproducibility

Always

### Anything else?

Please let me know if you need more information. Great project and thanks a lot for your effort.

**Comment by purejava** [comment]
The connection is closed when you end your program as `Connection` imlements `AutoClosable`:
https://github.com/purejava/keepassxc-proxy-access/blob/45985657b1f557bcb1749034d85714f9f5f65d6a/src/main/java/org/keepassxc/Connection.java#L24

The underlying socket (on Linux and Mac) or named pipe (on Windows) to KeePassXC is closed then:
https://github.com/purejava/keepassxc-proxy-access/blob/45985657b1f557bcb1749034d85714f9f5f65d6a/src/main/java/org/keepassxc/LinuxMacConnection.java#L126
https://github.com/purejava/keepassxc-proxy-access/blob/45985657b1f557bcb1749034d85714f9f5f65d6a/src/main/java/org/keepassxc/WindowsConnection.java#L82-L83

IMHO there is no need to close a connection manually.

**Comment by CallMeFlanby** [comment]
@purejava Thank you for your quick reply and your information, will try again on Monday and let you know if now works. ;)

**Comment by Flofler** [comment]
@purejava it's not true that a class implementing `AutoCloseable` does close automatically when a program ends. Therefore It needs to be created in a try-with-resources block.

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/AutoCloseable.html
> public interface AutoCloseable
> An object that may hold resources (such as file or socket handles) until it is closed. The [close()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/AutoCloseable.html#close()) method of an AutoCloseable object is called automatically when exiting a try-with-resources block for which the object has been declared in the resource specification header. This construction ensures prompt release, avoiding resource exhaustion exceptions and errors that may otherwise occur.

Furthermore, this library may is used in some long-running applications where it's not required for the connection to stay open all the time. So there should be a way to close the connection manually.

**Comment by purejava** [comment]
Fixed for the upcoming release that will provide:

https://github.com/purejava/keepassxc-proxy-access/blob/ac8be8bbf660efc7406e5134f79db3198923867d/src/main/java/org/purejava/KeepassProxyAccess.java#L514-L527
