### ISSUE TITLE
KeepassXC 2.4.3 is not compatible with this library

### ISSUE THREAD

**Issue by CallMeFlanby** [purejava/keepassxc-proxy-access#8]
Hello,

I don't if this is supposed to be a bug, that is why I didn't use the template.

We noticed that this library is not compatible with KeePassXC 2.4.3, the latest version from the original repository from Linux Mint 20.3 (e.g.).
We found that that the reason is just the string *PROXY_NAME*, found in the class *Connection.java*. You use:

    protected final String PROXY_NAME          = "org.keepassxc.KeePassXC.BrowserServer";

However in this version, this is not compatible. The proxy name in that version is:

    protected final String PROXY_NAME          = "kpxc_server";

I know that the latest available version in the Ubuntu repository for the latest LTS (22.04) is KeePassXC 2.6.6, however I cannot test if this library is compatible with it. 

In some methods you explicitly write, that they are only compatible with some versions (e.g. *delete-entry* and *request-autotype*), but I couldn't find any information which versions are compatible with the library.

Could you please add that information (something like "compatible with 2.7.0 and newer") or maybe update the code in order to make it compatible with older versions?

Thank you!

**Comment by purejava** [comment]
Hi,

thanks for pointing that out. This library is compatible with **KeePassXC >= 2.6.0**.
The reason for that is plain and simple that version 2.6.3 was the current release of KeePassXC when I implemented the library.

It's founded on [this protocol](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-protocol.md). I don't know, if this protocol was already used in KeePassXC 2.4.3, but I tested this library today with KeePassXC versions < 2.6.0 and it does not work. The changelog of KeePassXC states for versíon 2.6.0, that the way external applications connect with KeePassXC changed a lot.

I added a hint to the README, that the library requires KeePassXC >= 2.6.0.

There are no plans to make this library backwards compatible with earlier versions of KeePassXC.
