### ISSUE TITLE
Nonce increment incorrect when multiple bytes need changing

### ISSUE THREAD

**Issue by causalnet** [purejava/keepassxc-proxy-access#9]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/purejava/keepassxc-proxy-access/issues?q=) for duplicates

### Summary

Every so often, calls to keepassxc get stuck, which seems to be caused by nonce increment code not matching keepassxc's incremented nonces when multiple bytes need to be incremented

### What software is involved?

KeePassXC 2.7.4
Reproduced bug on both Windows and Linux OSes.

### Steps to Reproduce

Keep making KeepassXC calls, such as `Connection.getLogins()` although it can happen with any call that requires a response that needs incremented nonce matching.  Most will work, but about 1 in 256 will get stuck and block forever.  Debugging it, this seemed to be due to the nonce of KeepassXC's response not matching what `Connection.incrementNonce()` has calculated it should be.

This happens when the last nonce byte rolls over from 255 to 0.  Proxy access's increment code only increments the last byte, but KeepassXC's will increment the next byte (and so on) in this case.

### Expected Behavior

Nonce should match and call should work every time.

### Actual Behavior

Occasionally calls get stuck and block forever. 

### Reproducibility

Intermittent

**Comment by causalnet** [comment]
I wrote a repeating [test](https://github.com/causalnet/keepassxc-proxy-access/blob/fix/nonce-increment-test-without-fix/src/test/java/org/purejava/RepeatedLoginTest.java) case [in my fork](https://github.com/causalnet/keepassxc-proxy-access/tree/fix/nonce-increment-test-without-fix) that you might be able to use to reproduce this behaviour.  Since the generated nonce is random, I guess there's a 1/256 chance of getting the last byte of the nonce to be 255 which requires the next byte to be incremented.

I also made an additional unit test in another branch for testing just the nonce increment code, but haven't added this to the PR.  [This is the commit](https://github.com/purejava/keepassxc-proxy-access/commit/aae6be9c2413165308df70d596b59c9d383dd198).  I can add it if you want.

**Comment by purejava** [comment]
> I also made an additional unit test in another branch for testing just the nonce increment code, but haven't added this to the PR. [This is the commit](https://github.com/purejava/keepassxc-proxy-access/commit/aae6be9c2413165308df70d596b59c9d383dd198). I can add it if you want.

Thanks, that won't be necessary. I can find the unit test there.

Hopefully I'll find the time to look into this issue within this week, as unfortunately I am quite busy right now.

**Comment by purejava** [comment]
Thank you for your thorough analysis, for opening this issue, writing the unit test and developing a fix.

I am preparing a new release containing your fix now.

**Comment by causalnet** [comment]
Awesome, thanks!
